### ISSUE TITLE
Middleware does not use express best practices

### ISSUE THREAD

**Issue by flpvsk** [lahmatiy/express-open-in-editor#1]
Middleware should not care about `URL` it's used on and request methods it's triggered with. This all should be configured using express functionality.

E.g.

``` js
app.get('/open-in-editor', openInEditor());
```

is a more obvious and more flexible way of doing it, compared to:

``` js
app.use(openInEditor({
  url: '/open-in-editor'
});
```

Another benefit of suggested approach is that one could configure express to trigger middleware on any type of request: `POST`, `PUT`, `PATCH`... instead of limiting it to `GET`.

``` js
app.post('/open-in-editor', openInEditor());
```

**Comment by lahmatiy** [comment]
Agree.
I have no experience with `express`. But saw using of `app.get` in some articles recently. And thought about using it.
But think `app.use` using should be still possible.

Maybe you can PR to solve issue?

**Comment by flpvsk** [comment]
You can still use `app.use()` in any case. But behaviour should be different:

Trigger middleware on **any** request method to **any** path:

``` js
app.use(openInEditor());
```

Trigger middleware on **any** request method to `/open-in-editor`:

``` js
app.use('/open-in-editor', openInEditor());
```

Trigger middleware on **GET** request to `/open-in-editor`:

``` js
app.get('/open-in-editor', openInEditor());
```

I'm not sure if keeping old behaviour is a good idea. But of course it's your call.

**Comment by flpvsk** [comment]
More on the subject here: http://expressjs.com/guide/using-middleware.html

**Comment by lahmatiy** [comment]
I think that usage of anything should be as easy as possible, without any additional settings.
But if you insist that current behaviour is not appropriate, let's change it.

**Comment by flpvsk** [comment]
The only thing I'm not sure of are CORS headers. You're currently handling `OPTION` requests inside middleware. That makes it impossible to use it inside `app.get()`, because `OPTION` requests won't be passed to it.

You don't want to force users to use https://github.com/expressjs/cors right?

**Comment by lahmatiy** [comment]
Actually this extension is for development purposes. I'm not sure CORS will be an issue. But as I can see by your link there is workaround exist. We could add instructions about it to readme.
