### ISSUE TITLE
WebStorm open file fail. On macOS

### ISSUE THREAD

**Issue by gibson** [lahmatiy/express-open-in-editor#5]
I use webpack, my config is 

```
setup:              function (app) {
        app.use(openInEditor({editor: 'webstorm'}));
    }
```

When i try open file from component-inspector - your package trail first slash in file path and try to open file relative from webstorm path.

Temporary i fix it by comment line 

```
    filename = path
      .resolve('/', filename);
      // .replace(/^([a-z]+:)?\//i, '');
```

in index.js

**Comment by lahmatiy** [comment]
Fixed in [1.2.1](https://github.com/lahmatiy/express-open-in-editor/releases/tag/v1.2.1)
